services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habits
  
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    restart: unless-stopped
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--http-port", "7080"]
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - 7080:7080

  frontend:
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    build:
      context: frontend

  backend:
    container_name: backend
    restart: unless-stopped
    ports:
      - 5085:8080
    build:
      context: backend
    depends_on: 
      - postgres
    environment:
      HabitsDb__ConnectionString: "Server=postgres;Port=5432;Database=habits;User Id=postgres;Password=postgres;"
      HabitsDb__MigrateOnStartup: true

volumes:
  postgres:
  keycloak: