name: habits
services:

  app:
    env_file: .env
    restart: unless-stopped
    build:
      context: ./src
      args:
        - CONFIGURATION=Debug
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - 82:80
    profiles:
      - db-admin

volumes:
  pgdata:
  pgadmindata: